# Generated by Django 4.2 on 2023-04-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_full_name_product_fullname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-available', '-created')},
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=-1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='In stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Name'),
        ),
    ]
